import { wardenEvalWithConfig } from './core';
import type { Decision, WardenConfig } from './types';

export interface CodexRuleRecord {
  command: string;
  decision: Decision;
  reason: string;
}

function toCodexDecision(decision: Decision): 'allow' | 'prompt' | 'forbidden' {
  if (decision === 'allow') return 'allow';
  if (decision === 'ask') return 'prompt';
  return 'forbidden';
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function collectCandidateCommands(config: WardenConfig): string[] {
  const names = new Set<string>();
  for (const layer of config.layers) {
    for (const name of layer.alwaysAllow) names.add(name);
    for (const name of layer.alwaysDeny) names.add(name);
    for (const rule of layer.rules) names.add(rule.command);
  }

  // Starlark prefix rules operate on token arrays, so skip invalid names.
  return [...names]
    .map(n => n.trim())
    .filter(n => n.length > 0 && !/\s/.test(n))
    .sort();
}

export function buildCodexRuleRecords(config: WardenConfig): CodexRuleRecord[] {
  const records: CodexRuleRecord[] = [];
  for (const command of collectCandidateCommands(config)) {
    const result = wardenEvalWithConfig(command, config);
    records.push({
      command,
      decision: result.decision,
      reason: result.reason,
    });
  }
  return records;
}

export function generateCodexRules(config: WardenConfig): string {
  const lines: string[] = [
    '# Generated by claude-warden.',
    '# Regenerate with: pnpm codex:export-rules',
    '',
  ];

  for (const record of buildCodexRuleRecords(config)) {
    lines.push(
      `prefix_rule(pattern = [${quote(record.command)}], decision = ${quote(toCodexDecision(record.decision))}, justification = ${quote(`Warden: ${record.reason}`)})`,
    );
  }

  lines.push('');
  return lines.join('\n');
}
